import { fitnessImages } from "../data";
import { CaptureForm, FitMedia } from "../Primitives";
import s from "../Fitness.module.css";

export function Newsletter01(){return <section className={`${s.fitNewsletter} ${s.fitNews01}`}><span>14-DAY SIGNAL / 001</span><h2>GET BETTER<br/>INFORMATION.</h2><div><p>One field-tested session. One product teardown. No generic motivation.</p><CaptureForm mode="light"/></div><b>14</b></section>}
export function Newsletter02(){return <section className={`${s.fitNewsletter} ${s.fitNews02}`}><FitMedia src={fitnessImages[2]} alt="Trail runner crossing an alpine ridge"/><div className={s.dispatchCard}><span>FIELD DISPATCH / ALT. 2481</span><h2>TRAIN OUTSIDE<br/>THE FORECAST.</h2><p>Monthly trail reports, layer tests, and route-ready kit notes from athletes already out there.</p><CaptureForm mode="dark" button="SEND DISPATCH"/></div><div className={s.newsCoordinates}>46.8182° N / 8.2275° E</div></section>}
export function Newsletter03(){return <section className={`${s.fitNewsletter} ${s.fitNews03}`}><div className={s.dropClock}><span>DROP_006</span><b>08:14:22</b><small>VECTOR / SIGNAL ORANGE</small></div><div className={s.dropSignUp}><span>300 PAIRS / NO RESTOCK DATE</span><h2>ONE MESSAGE<br/>WHEN IT MOVES.</h2><p>Get the launch signal by email. No countdown sequence after that.</p><CaptureForm mode="lime" button="ALERT ME"/></div><FitMedia src={fitnessImages[5]} alt="Vector performance running shoe"/></section>}
export function Newsletter04(){return <section className={`${s.fitNewsletter} ${s.fitNews04}`}><div className={s.clubRing}><span>NTH</span><i/><b>365</b></div><div><span>NTH/FIELD CLUB</span><h2>MEMBERSHIP<br/>FOR THE WORK.</h2><p>Seasonal testing events, annual fit analysis, equipment servicing, and a shared training log that values consistency over rank.</p><ul><li>04 FIELD EVENTS / YEAR</li><li>01 ANNUAL FIT FILE</li><li>UNLIMITED EQUIPMENT SERVICE</li></ul><CaptureForm mode="dark" button="REQUEST ACCESS"/></div></section>}
export function Newsletter05(){return <section className={`${s.fitNewsletter} ${s.fitNews05}`}><div className={s.diagonalSignal}>SIGNAL / SIGNAL / SIGNAL / SIGNAL</div><div className={s.news05Copy}><span>BE FIRST, THEN GO TRAIN</span><h2>DROPS.<br/>TESTS.<br/>NOISE CUT.</h2><CaptureForm mode="light"/></div><div className={s.newsBars}>{[62,84,45,96,73,55,88].map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div></section>}
