import { fitnessImages, gear, type Gear } from "../data";
import { CartAction, FitMedia, SaveAction } from "../Primitives";
import s from "../Fitness.module.css";

function GearPrice({item}:{item:Gear}){return <span className={s.gearPrice}>{item.price}{item.compareAt&&<del>{item.compareAt}</del>}</span>}

export function Cards01(){return <section className={`${s.fitCards} ${s.fitCards01}`}><header><span>EQUIPMENT INDEX / LIVE STOCK</span><h2>TOOLS FOR<br/>REAL OUTPUT.</h2></header><div className={s.dataCards}>{gear.slice(0,4).map((item,index)=><article key={item.code}><div className={s.dataCardMedia}><FitMedia src={item.image} alt={item.name}/><span>{item.badge}</span><SaveAction/></div><div className={s.dataCardHead}><small>{item.code}</small><b>0{index+1}</b></div><h3>{item.name}</h3><p>{item.category}</p><div><GearPrice item={item}/><span>★ {item.rating}</span></div><CartAction/></article>)}</div></section>}

export function Cards02(){const item=gear[0];return <section className={`${s.fitCards} ${s.fitCards02}`}><div className={s.shoeConfig}><aside><span>{item.code}</span><h2>VECTOR<br/>CARBON<br/>TRAINER</h2><p>Road speed without the unstable stack.</p><strong>{item.price}</strong></aside><div className={s.shoeStage}><FitMedia src={item.image} alt={item.name}/><span>238G</span><span>8MM</span><span>PACE_03</span></div><div className={s.shoeControls}><span>SELECT COLOR</span><div className={s.colorGrid}><button aria-label="Electric lime" style={{background:"#c7ff00"}}/><button aria-label="Signal orange" style={{background:"#ef5a23"}}/><button aria-label="Carbon black" style={{background:"#161616"}}/></div><span>SELECT SIZE / US</span><div className={s.sizeGrid}>{[7,7.5,8,8.5,9,9.5,10,11].map(size=><button type="button" key={size}>{size}</button>)}</div><CartAction/></div></div></section>}

export function Cards03(){return <section className={`${s.fitCards} ${s.fitCards03}`}><header><div><span>SUPPLY DROP / 004</span><h2>THE 6AM KIT.</h2></div><p>Four objects for getting useful work done before the city starts talking.</p></header><div className={s.dropGrid}>{gear.slice(1,5).map((item,index)=><article key={item.code} className={s[`drop${index+1}`]}><FitMedia src={item.image} alt={item.name}/><div><small>{item.code} · {item.badge}</small><h3>{item.name}</h3><GearPrice item={item}/><CartAction small/></div></article>)}</div></section>}

export function Cards04(){return <section className={`${s.fitCards} ${s.fitCards04}`}><div className={s.compareTitle}><span>COMPARE / HOME STRENGTH</span><h2>CHOOSE<br/>YOUR LOAD.</h2></div><div className={s.compareGrid}>{gear.slice(1,4).map((item,index)=><article key={item.code}><span>0{index+1}</span><FitMedia src={item.image} alt={item.name}/><h3>{item.name}</h3><GearPrice item={item}/><dl><div><dt>FOOTPRINT</dt><dd>{["0.42m²","0.08m²","0.16m²"][index]}</dd></div><div><dt>RANGE</dt><dd>{["4—32kg","DAILY","2 LEVELS"][index]}</dd></div><div><dt>SETUP</dt><dd>{["02:10","00:00","00:30"][index]}</dd></div></dl><CartAction small/></article>)}</div></section>}

export function Cards05(){return <section className={`${s.fitCards} ${s.fitCards05}`}><header><span>STACK BUILDER / SESSION 04</span><h2>LOWER POWER</h2><p>Four movements. Three tools. Forty-two deliberate minutes.</p></header><div className={s.stackBuilder}><div className={s.stackTimeline}>{["WARM 08","LOAD 24","OUTPUT 06","DOWN 04"].map((step,index)=><span key={step} className={index===1?s.isActive:""}>{step}</span>)}</div><div className={s.stackProducts}>{gear.slice(0,3).map((item,index)=><article key={item.code}><span>0{index+1}</span><FitMedia src={item.image} alt={item.name}/><div><small>{item.code}</small><h3>{item.name}</h3><GearPrice item={item}/></div><button type="button" aria-label={`Remove ${item.name}`}>×</button></article>)}</div><aside><span>KIT TOTAL</span><strong>$591</strong><small>YOU SAVE $34 · DELIVERY $0</small><CartAction/></aside></div></section>}
