import { fitnessImages } from "../data";
import { FitMedia } from "../Primitives";
import s from "../Fitness.module.css";

export function Collage01(){return <section className={`${s.fitCollage} ${s.fitCollage01}`}><header><span>MOTION STUDY / SPRINT 001</span><h2>0.00—10.84</h2></header><div className={s.motionSequence}>{[0,0,8,10].map((image,index)=><figure key={index}><FitMedia src={fitnessImages[image]} alt="Sprint movement study"/><figcaption><span>0{index+1}</span>{["SET","DRIVE","BUILD","HOLD"][index]} <b>{["0.00","0.84","4.20","10.84"][index]}s</b></figcaption></figure>)}</div><p>Every frame removes a choice. The result is not effortless. It is precise.</p></section>}
export function Collage02(){return <section className={`${s.fitCollage} ${s.fitCollage02}`}><div className={s.blueprintGrid}/><span className={s.blueprintLabel}>EQUIPMENT LAB / STACK 32</span><FitMedia className={s.blueDumbbell} src={fitnessImages[4]} alt="Stack 32 adjustable dumbbells"/><FitMedia className={s.blueGrip} src={fitnessImages[10]} alt="Technical grip and mesh detail"/><div className={s.blueprintCopy}><h2>BUILT TO<br/>DISAPPEAR<br/>IN THE SET.</h2><dl><div><dt>01</dt><dd>Knurled neutral grip</dd></div><div><dt>02</dt><dd>Silent internal lock</dd></div><div><dt>03</dt><dd>Drop-tested cradle</dd></div></dl><a href="#cards">OPEN ENGINEERING FILE →</a></div></section>}
export function Collage03(){return <section className={`${s.fitCollage} ${s.fitCollage03}`}><div className={s.trailTitle}><span>FIELD REPORT / RIDGE 04</span><h2>ABOVE<br/>THE EASY<br/>LINE.</h2></div><FitMedia className={s.trailWide} src={fitnessImages[2]} alt="Runner moving along an alpine ridge"/><FitMedia className={s.trailGear} src={fitnessImages[5]} alt="Technical trail footwear"/><aside><span>ALTITUDE</span><b>2,481 M</b><span>DISTANCE</span><b>38.2 KM</b><span>SURFACE</span><b>LOOSE / WET</b></aside><p>One shoe, two layers, three weather changes. What stayed in the pack—and what earned its place.</p></section>}
export function Collage04(){return <section className={`${s.fitCollage} ${s.fitCollage04}`}><header><h2>THE 05:45 CLUB</h2><span>COMMUNITY CONTACT / WEEK 34</span></header><div className={s.communityWall}>{[11,9,1,0,2,8].map((image,index)=><figure key={index}><FitMedia src={fitnessImages[image]} alt="NTH Form community training"/><figcaption>{["@LEA.MOVES / 05:42","@TOMAS.RIDES / 06:08","@NOUR.LIFTS / 05:51","@SETH.SPRINTS / 06:12","@MAYA.TRAILS / 05:38","@SOUTHGYM / 05:59"][index]}</figcaption></figure>)}</div></section>}
export function Collage05(){return <section className={`${s.fitCollage} ${s.fitCollage05}`}><div className={s.sportPatch}><a href="#cards" className={s.patchRun}><FitMedia src={fitnessImages[0]} alt="Sprint"/><span>RUN / 18</span></a><a href="#cards" className={s.patchLift}><FitMedia src={fitnessImages[1]} alt="Strength"/><span>LOAD / 24</span></a><a href="#cards" className={s.patchRide}><FitMedia src={fitnessImages[9]} alt="Cycling"/><span>RIDE / 11</span></a><a href="#cards" className={s.patchRecover}><FitMedia src={fitnessImages[7]} alt="Recovery"/><span>RESET / 09</span></a><div><span>CHOOSE YOUR FIELD</span><h2>DIFFERENT WORK.<br/>SAME STANDARD.</h2></div></div></section>}
