import { fitnessFaqs, fitnessImages } from "../data";
import { FitMedia } from "../Primitives";
import s from "../Fitness.module.css";

function FitQuestions({ count=5, start=0, numbered=false }: { count?:number; start?:number; numbered?:boolean }) {
  return <div className={s.fitQuestions}>{fitnessFaqs.slice(start,start+count).map((item,index)=><details key={item.question} open={index===0}><summary>{numbered&&<span>{String(start+index+1).padStart(2,"0")}</span>}<b>{item.question}</b><i>+</i></summary><p>{item.answer}</p></details>)}</div>;
}

export function FAQ01(){return <section className={`${s.fitFaq} ${s.fitFaq01}`}><header><span>FIELD MANUAL / SUPPORT</span><h2>KNOW<br/>BEFORE<br/>YOU LOAD.</h2><p>Product, fit, fuel, and delivery guidance—written for decisions, not disclaimers.</p></header><FitQuestions count={5} numbered/></section>}
export function FAQ02(){return <section className={`${s.fitFaq} ${s.fitFaq02}`}><div className={s.coachImage}><FitMedia src={fitnessImages[1]} alt="Strength athlete preparing to deadlift"/><span>COACH DESK / LIVE 08—20 UTC</span></div><div><p className={s.coachTag}>GEAR ADVICE FROM PEOPLE WHO USE IT</p><h2>ASK A COACH.<br/>SKIP THE GUESS.</h2><FitQuestions count={4}/><a href="mailto:coach@nthform.example">START A FIT CONSULT →</a></div></section>}
export function FAQ03(){return <section className={`${s.fitFaq} ${s.fitFaq03}`}><header><div><span>SUPPORT CONSOLE</span><h2>SELECT A SYSTEM</h2></div><nav aria-label="FAQ filters"><button type="button" aria-pressed="true">01 / GEAR</button><button type="button">02 / FIT</button><button type="button">03 / FUEL</button><button type="button">04 / DELIVERY</button></nav></header><div className={s.consoleFaq}>{fitnessFaqs.slice(0,4).map((item,index)=><details key={item.question} open={index===0}><summary><span>Q_{index+1}</span><b>{item.question}</b><i>OPEN ↘</i></summary><p>{item.answer}</p></details>)}</div></section>}
export function FAQ04(){return <section className={`${s.fitFaq} ${s.fitFaq04}`}><span className={s.faqVertical}>THE LONG SET / 06 ANSWERS</span><h2>06</h2><div><p>QUESTIONS THAT SHOULD<br/>NOT SLOW THE SESSION.</p><FitQuestions count={6} numbered/></div></section>}
export function FAQ05(){return <section className={`${s.fitFaq} ${s.fitFaq05}`}><header><span>NTH/FORM DIAGNOSTIC</span><h2>WHAT’S THE HOLD-UP?</h2></header><div className={s.supportPath}><a href="#"><span>01</span><b>I NEED THE RIGHT SIZE</b><small>Fit tool · 90 sec →</small></a><a href="#"><span>02</span><b>MY ORDER IS MOVING</b><small>Live tracking →</small></a><a href="#"><span>03</span><b>MY GEAR NEEDS WORK</b><small>Repair desk →</small></a><a href="#"><span>04</span><b>I NEED A HUMAN</b><small>Coach desk →</small></a></div><aside><strong>AVG. RESPONSE</strong><b>08:42</b><span>MINUTES / OPEN HOURS</span></aside></section>}
