import { fitnessImages } from "../data";
import { CaptureForm, FitMedia, NthMark } from "../Primitives";
import s from "../Fitness.module.css";

function FitLinks(){return <div className={s.fitLinks}><div><b>SHOP</b><a href="#cards">Run</a><a href="#cards">Strength</a><a href="#cards">Fuel</a><a href="#cards">Recovery</a></div><div><b>SYSTEM</b><a href="#stories">Programs</a><a href="#stories">Field tests</a><a href="#reviews">Athletes</a><a href="#collages">Journal</a></div><div><b>SUPPORT</b><a href="#faqs">Fit desk</a><a href="#faqs">Delivery</a><a href="#faqs">Repairs</a><a href="#faqs">Returns</a></div></div>}

export function Footer01(){return <footer className={`${s.fitFooter} ${s.fitFooter01}`}><div className={s.footerStripe}><span>THE WORK CONTINUES</span><a href="#cards">BUILD A KIT →</a></div><div className={s.footerMassive}>NTH<span>/</span>FORM</div><div className={s.footer01Base}><span>©26 NTH/FORM PERFORMANCE SYSTEMS</span><div><a href="#">IG</a><a href="#">STRAVA</a><a href="#">YT</a></div><span>US / USD · PRIVACY · TERMS</span></div></footer>}
export function Footer02(){return <footer className={`${s.fitFooter} ${s.fitFooter02}`}><div className={s.logFooter}><span>TRAINING LOG / DISPATCH</span><h2>USEFUL SIGNAL.<br/>EVERY 14 DAYS.</h2><p>Field-tested sessions, gear notes, and one hard question worth taking into your week.</p><CaptureForm mode="lime"/></div><div className={s.footer02Right}><NthMark inverse/><FitLinks/><div><span>© 2026</span><span>NYC · BERLIN · TOKYO</span><span>VISA / MC / AMEX / PAYPAL</span></div></div></footer>}
export function Footer03(){return <footer className={`${s.fitFooter} ${s.fitFooter03}`}><div className={s.storeMap}><div className={s.mapGrid}/><span>40.7218° N<br/>74.0022° W</span><b>NYC_01</b></div><div className={s.storeInfo}><NthMark/><h2>TEST THE KIT.<br/>KEEP THE DATA.</h2><p>Run Vector on our 60 m lane. Load Stack 32. Leave with your fit profile—whether you buy or not.</p><address>48 Walker Street<br/>New York, NY 10013</address><div><span>MON—FRI 06—21</span><span>SAT—SUN 08—18</span></div><a href="#">BOOK A FIELD FIT →</a></div><FitLinks/></footer>}
export function Footer04(){return <footer className={`${s.fitFooter} ${s.fitFooter04}`}><header><span>COMMUNITY OUTPUT / LAST 7 DAYS</span><strong>18,492</strong><p>SESSIONS LOGGED</p></header><div className={s.scoreboard}><span>BERLIN<br/><b>3,804</b></span><span>CAIRO<br/><b>2,991</b></span><span>NEW YORK<br/><b>4,801</b></span><span>TOKYO<br/><b>3,220</b></span><span>EVERYWHERE ELSE<br/><b>3,676</b></span></div><div className={s.footer04Bottom}><NthMark inverse/><p>TRAIN TOGETHER / COMPARE ONLY WITH YESTERDAY.</p><div><a href="#">STRAVA ↗</a><a href="#">INSTAGRAM ↗</a><a href="#">EVENTS ↗</a></div></div></footer>}
export function Footer05(){return <footer className={`${s.fitFooter} ${s.fitFooter05}`}><FitMedia src={fitnessImages[8]} alt="Training partners pushing weighted sleds"/><div className={s.footer05Shade}/><div className={s.footer05Top}><NthMark inverse/><span>FIELD SYSTEMS / EST. 2026</span></div><div className={s.footer05Copy}><h2>SHOW UP<br/>WITH A PLAN.</h2><FitLinks/></div><div className={s.footer05Base}><span>US / USD</span><span>ACCESSIBILITY · TERMS · PRIVACY</span><span>© NTH/FORM</span></div></footer>}
