import { fitnessImages, fitnessReviews, gear } from "../data";
import { CartAction, FitCarousel, FitMedia } from "../Primitives";
import s from "../Fitness.module.css";

export function Carousel01(){return <section className={`${s.fitCarouselSection} ${s.fitCarousel01}`}><header><span>EQUIPMENT RAIL / 24 ITEMS</span><h2>BUILT FOR<br/>THE NEXT SET.</h2></header><FitCarousel label="Equipment systems" mode="wide">{gear.slice(1,5).map((item,index)=><article className={s.equipmentSlide} key={item.code}><span>0{index+1}</span><FitMedia src={item.image} alt={item.name}/><div><small>{item.code}</small><h3>{item.name}</h3><p>{item.category}</p><b>{item.price}</b><CartAction small/></div></article>)}</FitCarousel></section>}
export function Carousel02(){return <section className={`${s.fitCarouselSection} ${s.fitCarousel02}`}><header><h2>CHOOSE<br/>THE FIELD.</h2><p>Five disciplines. Different demands. No universal kit.</p></header><FitCarousel label="Training disciplines" mode="center">{[["RUN",fitnessImages[0],"18 SYSTEMS"],["LOAD",fitnessImages[1],"24 SYSTEMS"],["TRAIL",fitnessImages[2],"14 SYSTEMS"],["RIDE",fitnessImages[9],"11 SYSTEMS"],["RESET",fitnessImages[7],"09 SYSTEMS"]].map((item,index)=><a className={s.fieldSlide} href="#cards" key={item[0]}><FitMedia src={item[1]} alt=""/><span>0{index+1}</span><h3>{item[0]}</h3><small>{item[2]}</small></a>)}</FitCarousel></section>}
export function Carousel03(){return <section className={`${s.fitCarouselSection} ${s.fitCarousel03}`}><FitCarousel label="Field films" mode="cinema">{[["FILM_01","BEFORE THE CITY","Training before the day asks anything else.",fitnessImages[8]],["FILM_02","THE LONG RIDGE","What earns a place after kilometre thirty.",fitnessImages[2]],["FILM_03","DARK WATER","Fuel, rhythm, and staying calm without a wall.",fitnessImages[3]]].map(item=><article className={s.fieldFilm} key={item[0]}><FitMedia src={item[3]} alt="NTH Form field film"/><div><span>{item[0]} / 03:42</span><h3>{item[1]}</h3><p>{item[2]}</p><button type="button">PLAY FILM ▶</button></div></article>)}</FitCarousel></section>}
export function Carousel04(){return <section className={`${s.fitCarouselSection} ${s.fitCarousel04}`}><header><span>RECENTLY TESTED / YOUR FILE</span><h2>BACK TO THE KIT.</h2></header><FitCarousel label="Recently viewed gear" mode="compact">{gear.map(item=><article className={s.compactGear} key={item.code}><FitMedia src={item.image} alt={item.name}/><small>{item.code}</small><h3>{item.name}</h3><span>{item.price}</span><CartAction small/></article>)}</FitCarousel></section>}
export function Carousel05(){return <section className={`${s.fitCarouselSection} ${s.fitCarousel05}`}><header><span>ATHLETE LOGS / 04</span><h2>THE LONG ANSWER.</h2></header><FitCarousel label="Athlete training logs" mode="logs">{fitnessReviews.map((review,index)=><article className={s.athleteLog} key={review.name}><span>LOG_{String(index+1).padStart(3,"0")}</span><b>{review.metric}</b><blockquote>“{review.quote}”</blockquote><footer><FitMedia src={review.image} alt=""/><div><strong>{review.name}</strong><small>{review.discipline}<br/>{review.product}</small></div></footer></article>)}</FitCarousel></section>}
