import { fitnessImages } from "../data";
import { FitMedia } from "../Primitives";
import s from "../Fitness.module.css";

export function Story01(){return <section className={`${s.fitStory} ${s.fitStory01}`}><div className={s.materialMacro}><FitMedia src={fitnessImages[10]} alt="Macro view of technical mesh fabric"/><span>AIRFRAME / MESH MAP</span></div><div className={s.materialCopy}><span>MATERIAL SYSTEM / 08</span><h2>COOL WHERE<br/>THE WORK IS.</h2><p>Airframe does not chase an abstract idea of breathability. Its mesh density changes across the garment according to measured heat and friction zones.</p><dl><div><dt>34%</dt><dd>MORE AIRFLOW / SPINE</dd></div><div><dt>2×</dt><dd>ABRASION LAYER / SHOULDER</dd></div><div><dt>148G</dt><dd>MEN’S MEDIUM</dd></div></dl><a href="#cards">OPEN MATERIAL FILE →</a></div><div className={s.materialSwatches}><span>ZONE_01<i/></span><span>ZONE_02<i/></span><span>ZONE_03<i/></span></div></section>}
export function Story02(){return <section className={`${s.fitStory} ${s.fitStory02}`}><aside><span>FOUNDER NOTE / 001</span><b>“</b></aside><div className={s.founderWords}><h2>FITNESS RETAIL SELLS YOU A NEW SELF. WE’D RATHER SELL YOU A USEFUL TOOL.</h2><p>NTH/FORM began after a decade of coaching sessions where the best equipment was rarely the loudest object in the room. We build the shelf around training intent, then remove what doesn’t help.</p><strong>ARI NORTH<br/><small>FOUNDER / STRENGTH COACH</small></strong></div><FitMedia src={fitnessImages[8]} alt="NTH Form founder testing a sled session"/></section>}
export function Story03(){return <section className={`${s.fitStory} ${s.fitStory03}`}><header><span>VECTOR / ENGINEERING FILE 01</span><h2>THE SHOE,<br/>IN SECTION.</h2></header><div className={s.shoeArchitecture}><FitMedia src={fitnessImages[5]} alt="Vector carbon running shoe"/><span className={s.shoeCall01}>01<br/><b>WOVEN LOCKDOWN</b></span><span className={s.shoeCall02}>02<br/><b>FULL-LENGTH PLATE</b></span><span className={s.shoeCall03}>03<br/><b>WET-GRIP RUBBER</b></span></div><div className={s.archStats}><span>238 G</span><span>8 MM DROP</span><span>36 MM STACK</span><a href="#cards">SHOP VECTOR / $168 →</a></div></section>}
export function Story04(){return <section className={`${s.fitStory} ${s.fitStory04}`}><div className={s.recoveryIntro}><span>RECOVERY PROTOCOL / 10 MIN</span><h2>ADAPTATION<br/>HAPPENS<br/>BETWEEN.</h2><p>A short decompression sequence for hips, calves, and thoracic spine—designed to support tomorrow, not erase today.</p></div><FitMedia src={fitnessImages[7]} alt="Grid foam roller and pressure ball"/><div className={s.recoverySteps}>{[["02:00","CALF / SLOW PASS"],["03:00","HIP / HOLD + BREATHE"],["03:00","T-SPINE / EXTEND"],["02:00","DOWNSHIFT / NASAL"]].map((item,index)=><span key={item[0]}><b>0{index+1}</b>{item[1]}<i>{item[0]}</i></span>)}</div></section>}
export function Story05(){return <section className={`${s.fitStory} ${s.fitStory05}`}><div className={s.loopType}>RETURN / REPAIR / RELOAD /</div><div className={s.loopObject}><FitMedia src={fitnessImages[4]} alt="Stack 32 equipment ready for repair and reuse"/><span>PRODUCT LOOP / STACK 32</span></div><div className={s.loopCopy}><span>CIRCULAR EQUIPMENT / 05</span><h2>BUILT TO BE<br/>OPENED AGAIN.</h2><p>Stack 32 ships with replaceable selectors, serviceable plate locks, and a buy-back value visible from day one.</p><ol><li><b>01</b>TRAIN / 24 MONTHS</li><li><b>02</b>SERVICE / LOCAL</li><li><b>03</b>RETURN / $96 CREDIT</li><li><b>04</b>REBUILD / RELOAD</li></ol><a href="#cards">SEE THE PRODUCT LOOP →</a></div></section>}
