import { fitnessImages, fitnessReviews, gear } from "../data";
import { FitMedia } from "../Primitives";
import s from "../Fitness.module.css";

export function Reviews01(){return <section className={`${s.fitReviews} ${s.fitReviews01}`}><header><span>VERIFIED OUTPUT / N=2,840</span><h2>THE NUMBERS<br/>AFTER THE NOVELTY.</h2></header><div className={s.metricProof}>{[["92%","still use it at day 90"],["4.86","average field rating"],["18K+","sessions logged"]].map(item=><div key={item[0]}><b>{item[0]}</b><span>{item[1]}</span></div>)}</div><div className={s.proofQuotes}>{fitnessReviews.slice(0,2).map(review=><blockquote key={review.name}><p>“{review.quote}”</p><footer><b>{review.name}</b><span>{review.discipline}<br/>{review.product}</span></footer></blockquote>)}</div></section>}
export function Reviews02(){return <section className={`${s.fitReviews} ${s.fitReviews02}`}><aside><span>TRAINING LOG / VERIFIED</span><h2>NOTES FROM<br/>THE WORK.</h2><p>Reviews structured like a useful training entry: context, load, result.</p></aside><div className={s.logReviews}>{fitnessReviews.map((review,index)=><article key={review.name}><header><span>ENTRY_{String(index+1).padStart(3,"0")}</span><b>{review.metric}</b></header><p>{review.quote}</p><footer><strong>{review.name}</strong><span>{review.discipline}</span><small>{review.product}</small></footer></article>)}</div></section>}
export function Reviews03(){return <section className={`${s.fitReviews} ${s.fitReviews03}`}><header><h2>USED, NOT STYLED.</h2><span>COMMUNITY PROOF / WEEK 34</span></header><div className={s.reviewPhotos}>{fitnessReviews.map((review,index)=><figure key={review.name}><FitMedia src={review.image} alt={`${review.name} training`}/><figcaption><span>0{index+1} / ★★★★★</span><p>“{review.quote}”</p><b>{review.name} · {review.product}</b></figcaption></figure>)}</div></section>}
export function Reviews04(){const review=fitnessReviews[0];return <section className={`${s.fitReviews} ${s.fitReviews04}`}><div className={s.caseImage}><FitMedia src={fitnessImages[2]} alt="Road runner field test"/><span>CASE_118 / 8-WEEK BLOCK</span></div><div className={s.caseData}><span>VECTOR CARBON / VERIFIED PURCHASE</span><h2>{review.metric}</h2><b>10K PERSONAL BEST</b><blockquote>“{review.quote}”</blockquote><p>{review.name} · {review.discipline}</p></div><div className={s.caseTimeline}><span>WK01<i style={{height:"42%"}}/></span><span>WK03<i style={{height:"58%"}}/></span><span>WK05<i style={{height:"72%"}}/></span><span>WK08<i style={{height:"94%"}}/></span></div></section>}
export function Reviews05(){return <section className={`${s.fitReviews} ${s.fitReviews05}`}><div className={s.pressGrid}><span>OUTSIDE<br/><b>“REAL TOOLS, USEFULLY EXPLAINED.”</b></span><span>HYPEBEAST<br/><b>“FITNESS RETAIL WITH A POINT OF VIEW.”</b></span><span>RUNNER’S WORLD<br/><b>“VECTOR IS FAST WITHOUT THE THEATRE.”</b></span></div><div className={s.reviewMatrix}>{fitnessReviews.slice(0,3).map((review,index)=><article key={review.name}><span>{gear[index].code} / 5.0</span><p>{review.quote}</p><footer>{review.name}<b>{review.metric}</b></footer></article>)}</div></section>}
